In [1]:
import torch

In [7]:
# 가장 많이 쓰이는 float tensor
ft = torch.FloatTensor([[1, 2],
                      [3, 4]])
ft

tensor([[1., 2.],
        [3., 4.]])

In [6]:
lt = torch.LongTensor([[1, 2], [3, 4]]) # Index 값에 많이 이용..?
lt

tensor([[1, 2],
        [3, 4]])

In [9]:
bt = torch.ByteTensor([[1, 0], [0, 1]])
bt

tensor([[1, 0],
        [0, 1]], dtype=torch.uint8)

In [11]:
x = torch.FloatTensor(3, 2)
x

tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])

## NumPy Compatiblity

In [12]:
import numpy as np

x = np.array([[1, 2],
             [3, 4]])
x

array([[1, 2],
       [3, 4]])

In [13]:
x = torch.from_numpy(x)
x

tensor([[1, 2],
        [3, 4]], dtype=torch.int32)

In [14]:
x = x.numpy()
x

array([[1, 2],
       [3, 4]])

## Tensor Type-casting

In [15]:
ft.long()

tensor([[1, 2],
        [3, 4]])

In [16]:
lt.float()

tensor([[1., 2.],
        [3., 4.]])

## Get Shape

In [18]:
x = torch.FloatTensor([
    [[1, 2],
    [3, 4]],
    [[5, 6],
     [7, 8]],
    [[9, 10],
    [11, 12]]
])
x

tensor([[[ 1.,  2.],
         [ 3.,  4.]],

        [[ 5.,  6.],
         [ 7.,  8.]],

        [[ 9., 10.],
         [11., 12.]]])

In [19]:
print(x.size())
print(x.shape)

torch.Size([3, 2, 2])
torch.Size([3, 2, 2])


In [20]:
print(x.dim())
print(len(x.size()))

3
3


In [21]:
print(x.size(1))
print(x.shape[1])

2
2


In [22]:
print(x.size(-1))
print(x.shape[-1])

2
2


## Tensor Operations

In [23]:
a = torch.FloatTensor([[1, 2], 
                      [3, 4]])
b = torch.FloatTensor([[2, 2], 
                       [3, 3]])


In [24]:
a + b

tensor([[3., 4.],
        [6., 7.]])

In [25]:
a - b

tensor([[-1.,  0.],
        [ 0.,  1.]])

In [26]:
a * b

tensor([[ 2.,  4.],
        [ 9., 12.]])

In [32]:
a / b  

tensor([[0.5000, 1.0000],
        [1.0000, 1.3333]])

In [29]:
a == b

tensor([[False,  True],
        [ True, False]])

In [30]:
a != b

tensor([[ True, False],
        [False,  True]])

In [31]:
a ** b

tensor([[ 1.,  4.],
        [27., 64.]])

## Inplace Operations
- 연산 수행 시 언더바를 붙여서, 해당 값을 덮어씌운다...
- 새로운 변수에 할당하지 않고 연산 후의 값을 기존 변수에 덮어 씌우는 것

In [33]:
print(a)
print(a.mul(b))
print(a)
print(a.mul_(b))
print(a)

tensor([[1., 2.],
        [3., 4.]])
tensor([[ 2.,  4.],
        [ 9., 12.]])
tensor([[1., 2.],
        [3., 4.]])
tensor([[ 2.,  4.],
        [ 9., 12.]])
tensor([[ 2.,  4.],
        [ 9., 12.]])


## Sum, Mean (Dimension Reducing Operations)

In [34]:
x = torch.FloatTensor([[1, 2], 
                      [3, 4]])
x

tensor([[1., 2.],
        [3., 4.]])

In [35]:
print(x.sum())
print(x.mean())

tensor(10.)
tensor(2.5000)


In [37]:
# 특정 dimension에 대해서만 계산 범위 지정
print(x.sum(dim=0))
print(x.sum(dim=1))
print(x.sum(dim=-1))

tensor([4., 6.])
tensor([3., 7.])
tensor([3., 7.])
