# PyTorch Useful Methods

In [2]:
import torch

### expand: copy the given tensor and concat those at desired dimension.

In [3]:
x = torch.FloatTensor([[[1, 2]],
                       [[3, 4]]])
print(x.size())

torch.Size([2, 1, 2])


In [4]:
y = x.expand(*[2, 3, 2])

print(y)
print(y.size())

tensor([[[1., 2.],
         [1., 2.],
         [1., 2.]],

        [[3., 4.],
         [3., 4.],
         [3., 4.]]])
torch.Size([2, 3, 2])


#### Implement expand with cat.

In [8]:
y = torch.cat([x, x, x], dim=1)

print(y)
print(y.size())

tensor([[[1., 2.],
         [1., 2.],
         [1., 2.]],

        [[3., 4.],
         [3., 4.],
         [3., 4.]]])
torch.Size([2, 3, 2])


### randperm: Random Permutation

In [5]:
x = torch.randperm(10)

print(x)
print(x.size())

tensor([1, 9, 6, 4, 0, 7, 3, 5, 2, 8])
torch.Size([10])


### argmax: Return index of maximum values

In [13]:
x = torch.randperm(3**3).reshape(3, 3, -1)

print(x)
print(x.size())

tensor([[[24, 20,  7],
         [22, 25, 21],
         [ 6,  1,  4]],

        [[26, 12,  5],
         [17,  0,  2],
         [19,  9, 16]],

        [[23, 15, 13],
         [14, 18,  8],
         [11,  3, 10]]])
torch.Size([3, 3, 3])


In [7]:
y = x.argmax(dim=-1)

print(y)
print(y.size())

tensor([[2, 1, 0],
        [2, 1, 2],
        [2, 1, 0]])
torch.Size([3, 3])


`argmax` 함수는 주어진 텐서에서 가장 큰 값의 인덱스를 반환하는 함수입니다. 이 함수는 주로 머신러닝과 딥러닝에서 클래스 분류 결과를 처리할 때 많이 사용됩니다. 예를 들어, 모델의 출력이 여러 클래스에 대한 확률일 때, `argmax`를 사용하여 가장 높은 확률을 가진 클래스를 선택할 수 있습니다.

### `argmax` 함수의 기본 개념

- **기능**: `argmax`는 특정 차원(dimension)에서 가장 큰 값이 위치한 인덱스를 반환합니다.
- **입력**: `argmax`는 텐서와 선택적인 `dim` 파라미터를 입력으로 받습니다.
  - `dim`은 어떤 차원에서 최대 값을 찾을 것인지 지정합니다.
  - `dim`을 지정하지 않으면, 텐서를 1차원으로 펼친 후 전체에서 가장 큰 값의 인덱스를 반환합니다.
- **출력**: 가장 큰 값의 인덱스를 담고 있는 텐서가 반환됩니다. 반환되는 텐서의 크기는 원본 텐서에서 `dim` 차원이 제거된 형태가 됩니다.

### 예시

```python
import torch

# 1차원 텐서의 예시
a = torch.tensor([1, 3, 2])
index = torch.argmax(a)
print(index)  # 출력: tensor(1), 인덱스 1이 가장 큰 값(3)의 위치

# 2차원 텐서의 예시
b = torch.tensor([[1, 2, 3],
                  [4, 5, 6]])
index = torch.argmax(b, dim=0)  # 각 열에서 최대 값의 인덱스
print(index)  # 출력: tensor([1, 1, 1])

index = torch.argmax(b, dim=1)  # 각 행에서 최대 값의 인덱스
print(index)  # 출력: tensor([2, 2])
```

### 파라미터

- **`dim`**: `argmax` 함수에 전달할 수 있는 중요한 파라미터로, 특정 차원을 지정합니다. `dim`을 설정하면, 해당 차원에 따라 최대 값을 찾아 인덱스를 반환합니다.
  - 예를 들어, `dim=0`으로 설정하면 각 열(column)에서 최대 값의 인덱스를 반환합니다.
  - `dim=1`으로 설정하면 각 행(row)에서 최대 값의 인덱스를 반환합니다.

### 실제 활용 예

- **분류 모델의 예측**: 모델의 출력이 각 클래스에 대한 확률값(또는 점수)으로 나타날 때, `argmax`를 사용하여 가장 높은 확률을 가진 클래스를 선택합니다.
  
  ```python
  # 예를 들어, 모델의 출력이 다음과 같다면
  output = torch.tensor([0.1, 0.7, 0.2])
  
  # 가장 높은 확률을 가진 클래스의 인덱스를 찾습니다
  predicted_class = torch.argmax(output)
  print(predicted_class)  # 출력: tensor(1)
  ```

### 요약

- **`argmax`**는 주어진 텐서에서 가장 큰 값의 인덱스를 반환하는 함수입니다.
- **차원 지정**: `dim` 파라미터를 통해 특정 차원에서 최대 값을 찾을 수 있습니다.
- **주로 사용되는 경우**: 분류 문제에서 모델의 예측 값을 기반으로 가장 가능성이 높은 클래스를 선택할 때 자주 사용됩니다.

`argmax`는 텐서의 데이터에서 가장 중요한 요소를 빠르게 식별하는 데 매우 유용한 함수입니다.

### topk: Return tuple of top-k values and indices.

`topk` 함수는 PyTorch에서 주어진 텐서에서 상위 `k`개의 값과 그에 대응하는 인덱스를 반환하는 함수입니다. 이 함수는 `argmax`와 유사하지만, `argmax`가 가장 큰 값 하나의 인덱스를 반환하는 것과 달리, `topk`는 여러 개의 상위 값을 선택할 수 있습니다.

### `topk` 함수의 기본 개념

- **기능**: 주어진 텐서에서 상위 `k`개의 값과 그 값들의 인덱스를 반환합니다.
- **입력**:
  - 텐서: `topk`를 적용할 대상 텐서.
  - `k`: 반환할 상위 값의 개수.
  - `dim`: 어떤 차원에서 상위 `k`개를 찾을지 지정합니다. (기본값은 `-1`, 즉 마지막 차원)
  - `largest`: `True`일 경우 가장 큰 값 `k`개를 반환하고, `False`일 경우 가장 작은 값 `k`개를 반환합니다.
  - `sorted`: `True`일 경우 반환된 값들이 내림차순(큰 값에서 작은 값 순)으로 정렬됩니다. (기본값: `True`)

- **출력**: `(values, indices)`의 튜플 형태로 반환되며,
  - `values`는 상위 `k`개의 값을 포함한 텐서입니다.
  - `indices`는 그 값들이 위치한 인덱스를 포함한 텐서입니다.

### 예시

```python
import torch

# 1차원 텐서의 예시
a = torch.tensor([1, 3, 5, 7, 9])
values, indices = torch.topk(a, k=3)
print(values)   # 출력: tensor([9, 7, 5])
print(indices)  # 출력: tensor([4, 3, 2])

# 2차원 텐서의 예시
b = torch.tensor([[1, 6, 3],
                  [4, 8, 2],
                  [5, 7, 9]])
values, indices = torch.topk(b, k=2, dim=1)
print(values)   # 각 행에서 상위 2개의 값: tensor([[6, 3], [8, 4], [9, 7]])
print(indices)  # 상위 2개 값의 인덱스: tensor([[1, 2], [1, 0], [2, 1]])
```

### 파라미터

- **`k`**: 반환할 상위 값의 개수를 지정합니다.
- **`dim`**: 상위 값을 찾을 차원을 지정합니다.
  - 예를 들어, `dim=0`이면 각 열에서 상위 `k`개를 찾고, `dim=1`이면 각 행에서 상위 `k`개를 찾습니다.
- **`largest`**: `True`일 경우 가장 큰 값들을 반환하고, `False`일 경우 가장 작은 값들을 반환합니다.
- **`sorted`**: `True`일 경우 반환된 값들이 내림차순으로 정렬됩니다.

### 실제 활용 예

- **분류 모델의 다중 예측 결과**:
  - 모델이 여러 클래스를 예측할 때, 상위 `k`개의 예측 결과를 확인하고자 할 때 사용할 수 있습니다. 예를 들어, 이미지 분류 모델에서 모델이 예측한 상위 `k`개의 클래스와 그 확률을 보고자 할 때 유용합니다.

  ```python
  # 예를 들어, 모델의 출력이 다음과 같다면
  output = torch.tensor([0.1, 0.7, 0.2, 0.5])
  
  # 상위 2개의 값을 찾습니다
  values, indices = torch.topk(output, k=2)
  print(values)   # 출력: tensor([0.7, 0.5])
  print(indices)  # 출력: tensor([1, 3])
  ```

  이 예에서는 두 번째 요소(`0.7`)와 네 번째 요소(`0.5`)가 상위 2개의 값으로 선택되었습니다.

### 요약

- **`topk` 함수**는 텐서에서 상위 `k`개의 값과 그 인덱스를 반환합니다.
- **차원 지정**: `dim` 파라미터를 사용해 어느 차원에서 상위 `k`개를 찾을지 지정할 수 있습니다.
- **주로 사용되는 경우**: 여러 클래스에 대한 확률을 다루는 분류 문제에서 상위 `k`개의 예측 결과를 선택할 때 자주 사용됩니다.

`topk` 함수는 데이터에서 중요한 상위 요소들을 빠르게 식별할 수 있는 매우 유용한 도구입니다.

In [19]:
values, indices = torch.topk(x, k=1, dim=-1)

print(values, indices)
print(values.size())
print(indices.size())

tensor([[[24],
         [25],
         [ 6]],

        [[26],
         [17],
         [19]],

        [[23],
         [18],
         [11]]]) tensor([[[0],
         [1],
         [0]],

        [[0],
         [0],
         [0]],

        [[0],
         [1],
         [0]]])
torch.Size([3, 3, 1])
torch.Size([3, 3, 1])


Note that topk didn't reduce the dimension, even in $k=1$ case.

In [16]:
print(values.squeeze(-1))
print(indices.squeeze(-1))

tensor([[24, 25,  6],
        [26, 17, 19],
        [23, 18, 11]])
tensor([[0, 1, 0],
        [0, 0, 0],
        [0, 1, 0]])


In [17]:
print(x.argmax(dim=-1) == indices.squeeze(-1))

tensor([[True, True, True],
        [True, True, True],
        [True, True, True]])


In [11]:
_, indices = torch.topk(x, k=2, dim=-1)
print(indices.size())

print(x.argmax(dim=-1) == indices[:, :, 0])

torch.Size([3, 3, 2])
tensor([[True, True, True],
        [True, True, True],
        [True, True, True]])


### Sort by using topk

In [12]:
target_dim = -1
values, indices = torch.topk(x,
                             k=x.size(target_dim),
                             largest=True)

print(values)

tensor([[[25, 18,  9],
         [16,  8,  0],
         [24, 20, 14]],

        [[17,  4,  1],
         [22,  7,  2],
         [12, 10,  5]],

        [[23, 15, 13],
         [21, 19,  3],
         [26, 11,  6]]])


### Topk by using sort

In [21]:
k=1
values, indices = torch.sort(x, dim=-1, descending=True)
values, indices = values[:, :, :k], indices[:, :, :k]

print(values, indices)
print(values.squeeze(-1))
print(indices.squeeze(-1))

tensor([[[24],
         [25],
         [ 6]],

        [[26],
         [17],
         [19]],

        [[23],
         [18],
         [11]]]) tensor([[[0],
         [1],
         [0]],

        [[0],
         [0],
         [0]],

        [[0],
         [1],
         [0]]])
tensor([[24, 25,  6],
        [26, 17, 19],
        [23, 18, 11]])
tensor([[0, 1, 0],
        [0, 0, 0],
        [0, 1, 0]])


### masked_fill: fill the value if element of mask is True.

In [14]:
x = torch.FloatTensor([i for i in range(3**2)]).reshape(3, -1)

print(x)
print(x.size())

tensor([[0., 1., 2.],
        [3., 4., 5.],
        [6., 7., 8.]])
torch.Size([3, 3])


In [15]:
mask = x > 4

print(mask)

tensor([[False, False, False],
        [False, False,  True],
        [ True,  True,  True]])


In [16]:
y = x.masked_fill(mask, value=-1)

print(y)

tensor([[ 0.,  1.,  2.],
        [ 3.,  4., -1.],
        [-1., -1., -1.]])


### Ones and Zeros

In [17]:
print(torch.ones(2, 3))
print(torch.zeros(2, 3))

tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [18]:
x = torch.FloatTensor([[1, 2, 3],
                       [4, 5, 6]])
print(x.size())

torch.Size([2, 3])


In [19]:
print(torch.ones_like(x))
print(torch.zeros_like(x))

tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])
