# PyTorch Tensor Operations

In [4]:
import torch

## Arithmetic Element-wise Operations

In [6]:
a = torch.FloatTensor([[1, 2],
                       [3, 4]])
b = torch.FloatTensor([[2, 2],
                       [3, 3]])
print(a.shape, a.dim())

torch.Size([2, 2]) 2


In [7]:
a + b

tensor([[3., 4.],
        [6., 7.]])

In [8]:
a - b

tensor([[-1.,  0.],
        [ 0.,  1.]])

In [9]:
a * b

tensor([[ 2.,  4.],
        [ 9., 12.]])

In [10]:
a / b

tensor([[0.5000, 1.0000],
        [1.0000, 1.3333]])

In [11]:
a == b

tensor([[False,  True],
        [ True, False]])

In [12]:
a != b

tensor([[ True, False],
        [False,  True]])

In [13]:
a ** b

tensor([[ 1.,  4.],
        [27., 64.]])

## Inplace Operations

Inplace Operation(인플레이스 연산)은 기존의 데이터를 덮어쓰면서 연산을 수행하는 작업을 의미합니다. 즉, 새로운 메모리 공간을 할당하지 않고, 기존 텐서의 값이 직접 변경됩니다. PyTorch에서는 이런 인플레이스 연산을 수행할 때 주로 연산자 뒤에 _(언더스코어)를 붙여 표현합니다.

### PyTorch에서 자주 사용되는 인플레이스 연산자:
- add_(): 덧셈
- sub_(): 뺄셈
- mul_(): 곱셈
- div_(): 나눗셈
- zero_(): 모든 값을 0으로 설정
- fill_(): 특정 값으로 모든 요소를 채움

### 인플레이스 연산의 장단점:
- 장점: 메모리 사용을 줄일 수 있습니다. 새로운 텐서를 생성하지 않기 때문에 메모리 효율성이 증가합니다.
- 단점: 원본 데이터가 변경되므로, 의도치 않은 데이터 손실이나 에러가 발생할 수 있습니다. 특히, 그래디언트 연산을 포함한 역전파 과정에서는 인플레이스 연산이 문제를 일으킬 수 있기 때문에 주의가 필요합니다.

In [14]:
print(a)
print(a.mul(b))
print(a)
print(a.mul_(b))
print(a)

tensor([[1., 2.],
        [3., 4.]])
tensor([[ 2.,  4.],
        [ 9., 12.]])
tensor([[1., 2.],
        [3., 4.]])
tensor([[ 2.,  4.],
        [ 9., 12.]])
tensor([[ 2.,  4.],
        [ 9., 12.]])


## Sum, Mean (Dimension Reducing Operations)

In [29]:
x = torch.FloatTensor([[1, 2],
                       [3, 4]])

In [30]:
print(x.sum())
print(x.mean())

tensor(10.)
tensor(2.5000)


dim 파라미터는 PyTorch에서 텐서 연산을 수행할 때 특정 차원(dimension)을 기준으로 연산을 수행하도록 지정하는 역할을 합니다. dim 파라미터는 텐서의 어느 축(axis) 또는 차원에서 연산이 이루어져야 하는지를 결정합니다.

- 차원 0 (dim=0): 행(row)에 해당하는 차원 (위에서 아래로, 수직)
- 차원 1 (dim=1): 열(column)에 해당하는 차원 (왼쪽에서 오른쪽으로, 수평)
- 차원 -1 (dim=-1): 마지막 차원을 의미합니다. 이 경우에는 차원 1과 동일합니다.

In [35]:
print(x.sum(dim=0), x.sum(dim=0).shape)
print(x.sum(dim=-1), x.sum(dim=-1).shape)

tensor([4., 6.]) torch.Size([2])
tensor([3., 7.]) torch.Size([2])


5차원 텐서는 (D0, D1, D2, D3, D4)의 모양을 가집니다. 예를 들어, (2, 3, 4, 2, 2) 크기의 텐서를 생성해 보겠습니다.

In [36]:
x = torch.round(torch.randn(2, 3, 4, 2, 2))
x

tensor([[[[[-1.,  1.],
           [-0., -0.]],

          [[-1.,  1.],
           [-1.,  1.]],

          [[ 0.,  2.],
           [-0.,  1.]],

          [[ 0.,  2.],
           [-2.,  2.]]],


         [[[-1.,  1.],
           [-3., -1.]],

          [[-0.,  2.],
           [-1.,  2.]],

          [[ 1.,  0.],
           [-0.,  2.]],

          [[-1., -0.],
           [ 0.,  0.]]],


         [[[ 0.,  0.],
           [ 0.,  2.]],

          [[ 0., -1.],
           [-1., -1.]],

          [[ 2.,  1.],
           [-1.,  1.]],

          [[-1., -0.],
           [ 1., -1.]]]],



        [[[[-1., -0.],
           [-1.,  1.]],

          [[ 1.,  0.],
           [ 1., -1.]],

          [[ 1., -1.],
           [-1., -1.]],

          [[ 0., -1.],
           [-0.,  0.]]],


         [[[-1., -1.],
           [ 3., -1.]],

          [[ 1., -1.],
           [ 0., -1.]],

          [[-0., -1.],
           [ 0.,  1.]],

          [[-1.,  2.],
           [ 2.,  1.]]],


         [[[ 0.,  0.],
     

- dim=0: 첫 번째 차원을 따라 합산합니다. (D1, D2, D3, D4) 모양의 텐서가 됩니다.
- dim=1: 두 번째 차원을 따라 합산합니다. (D0, D2, D3, D4) 모양의 텐서가 됩니다.
- dim=2: 세 번째 차원을 따라 합산합니다. (D0, D1, D3, D4) 모양의 텐서가 됩니다.
- dim=-1: 마지막 차원을 따라 합산합니다. (D0, D1, D2, D3) 모양의 텐서가 됩니다.

각 차원에서의 합산은 해당 차원에 위치한 요소들을 합하여 그 차원을 제거하는 방식으로 이루어지며, 나머지 차원은 그대로 유지됩니다.

In [37]:
print(x.sum())
print(x.sum(dim=0))

tensor(4.)
tensor([[[[-2.,  1.],
          [-1.,  1.]],

         [[ 0.,  1.],
          [ 0.,  0.]],

         [[ 1.,  1.],
          [-1.,  0.]],

         [[ 0.,  1.],
          [-2.,  2.]]],


        [[[-2.,  0.],
          [ 0., -2.]],

         [[ 1.,  1.],
          [-1.,  1.]],

         [[ 1., -1.],
          [ 0.,  3.]],

         [[-2.,  2.],
          [ 2.,  1.]]],


        [[[ 0.,  0.],
          [-1.,  0.]],

         [[-1., -3.],
          [ 0., -1.]],

         [[ 2.,  1.],
          [-2.,  1.]],

         [[-1.,  0.],
          [ 1.,  2.]]]])


## Broadcast in Operations


Tensor의 연산에서 같은 모양(Shape)을 가지는 텐서끼리의 연산이 기본적으로 가장 직관적이고 일반적입니다. 그러나 PyTorch와 같은 라이브러리에서는 모양이 다르더라도 특정 조건을 만족하면 연산이 가능합니다. 이를 **브로드캐스팅(Broadcasting)**이라고 합니다.

- 두 텐서의 모양이 다를 때, 특정 규칙에 따라 작은 텐서의 모양이 자동으로 큰 텐서와 맞춰진 후 연산이 수행됩니다.
### 브로드캐스팅 규칙:
- 뒤에서부터(오른쪽에서부터) 차원을 비교하며, 각 차원에서 모양이 같거나 하나의 차원이 1이면 연산이 가능합니다.
- 차원이 1인 텐서는 자동으로 반복되어(복제되어) 큰 텐서의 차원에 맞춰집니다


What we did before,

In [38]:
x = torch.FloatTensor([[1, 2]])
y = torch.FloatTensor([[4, 8]])

print(x.size())
print(y.size())

torch.Size([1, 2])
torch.Size([1, 2])


In [39]:
z = x + y
print(z)
print(z.size())

tensor([[ 5., 10.]])
torch.Size([1, 2])


Broadcast feature provides operations between different shape of tensors.

### Tensor + Scalar

In [40]:
x = torch.FloatTensor([[1, 2],
                       [3, 4]])
y = 1

print(x.size())

torch.Size([2, 2])


In [41]:
z = x + y
print(z)
print(z.size())

tensor([[2., 3.],
        [4., 5.]])
torch.Size([2, 2])


### Tensor + Vector

In [42]:
x = torch.FloatTensor([[1, 2],
                       [4, 8]])
y = torch.FloatTensor([3,
                       5])

print(x.size())
print(y.size())

torch.Size([2, 2])
torch.Size([2])


In [43]:
z = x + y
print(z)
print(z.size())

tensor([[ 4.,  7.],
        [ 7., 13.]])
torch.Size([2, 2])


In [46]:
x = torch.FloatTensor([[[1, 2]]])
y = torch.FloatTensor([3,
                       5])

print(x.size(), x.dim())
print(y.size())

torch.Size([1, 1, 2]) 3
torch.Size([2])


In [47]:
z = x + y
print(z)
print(z.size())

tensor([[[4., 7.]]])
torch.Size([1, 1, 2])


### Tensor + Tensor

In [48]:
x = torch.FloatTensor([[1, 2]])
y = torch.FloatTensor([[3],
                       [5]])

print(x.size())
print(y.size())

torch.Size([1, 2])
torch.Size([2, 1])


In [49]:
z = x + y
print(z)
print(z.size())

tensor([[4., 5.],
        [6., 7.]])
torch.Size([2, 2])


Note that you need to be careful before using broadcast feature.

### Failure Case

In [24]:
x = torch.FloatTensor([[[1, 2],
                        [4, 8]]])
y = torch.FloatTensor([[1, 2, 3],
                       [4, 5, 6],
                       [7, 8, 9]])

print(x.size())
print(y.size())

z = x + y

torch.Size([1, 2, 2])
torch.Size([3, 3])


RuntimeError: The size of tensor a (2) must match the size of tensor b (3) at non-singleton dimension 2